// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddulmdacvcnkdkzwmsbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdWxtZGFjdmNua2Rrendtc2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1NDEwMzIsImV4cCI6MjA5NTExNzAzMn0.vCyVOzsppbV-oiM9VcbOeUfRMpAG-UK4eq8US4b5x8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});